#!/bin/sh
###############################################################
# SPDX-License-Identifier: BSD-2-Clause-Patent
# SPDX-FileCopyrightText: 2019-2020 the prplMesh contributors (see AUTHORS.md)
# This code is subject to the terms of the BSD+Patent license.
# See LICENSE file for more details.
###############################################################
${INSTALL_DIR}/scripts/prplmesh_utils.sh start -m c "$@"
tail -f /dev/null # hack so the script will not exit forcing the container to stop
