pull_request_rules:
  - name: Automatic rebase and merge on approval
    conditions:
      - "#approved-reviews-by>=2" # Require at least two approving reviewers
      - "#changes-requested-reviews-by=0" # Changes requested blocks the merge
      - "label=ready for merge" # Must have ready for merge label
      - "label!=don't merge" # Don't merge label blocks the merge
      - "#status-failure=0"
      # Just to be sure that we don't consider it as passed when the status checks haven't even
      # started yet.
      - "#status-success>=3"
    actions:
      merge:
        method: rebase # Merge with rebase
        rebase_fallback: null # Manual intervention needed if that doesn't work
        # If not up-to-date with master, bring it up-to-date first.
        # Use rebase for bringing up-to-date
        # Use "smart" to do the rebase one-by-one, in case multiple PRs need to be
        # rebased.
        strict: smart
        strict_method: rebase

  - name: Remove redundant labels
    conditions:
      - "merged"
    actions:
      label:
        # These labels are potentially confusing for merged PRs, so remove them
        remove: ["ready for merge", "help wanted", "don't merge", "wait for platform test"]
