@startuml
 -> beerocks_cli: beerocks_cli -c \n"bml_set_wifi_credentials <new_ssid> <new_pass> [<security>] [<vap_id>] [<force>]"
beerocks_cli -> beerocks_cli: cli_bml::set_wifi_credentials_caller(args)
beerocks_cli -> beerocks_cli: cli_bml::set_wifi_credentials(\n args.stringArgs[0],\n args.stringArgs[1],\n args.intArgs[2],\n args.intArgs[3],\n args.intArgs[4])
beerocks_cli -> beerocks_cli: bml_set_wifi_credentials(\n ctx, \nssid.c_str(), \npass.c_str(), \nsec, \nvap_id, \nforce)
beerocks_cli -> bml_internal: set_wifi_credentials(\n const std::string ssid,\n const std::string pass,\n int sec,\n int vap_id,\n int force)
bml_internal -> controller: message_com::send_cmdu(m_sockMaster, ACTION_BML_WIFI_CREDENTIALS_UPDATE_REQUEST)
note right: // TODO: trigger auto-config, probaly\n it will be a good idea to change the message\n to "ACTION_BML_UPDATE_CONFIGURATION_REQUEST"
@enduml