@startuml
 -> beerocks_cli: beerocks_cli -c \n"bml_update_wifi_credentials <al-mac>"
beerocks_cli -> beerocks_cli: cli_bml::update_wifi_credentials_caller(args)
beerocks_cli -> beerocks_cli: cli_bml::update_wifi_credentials(\n args.stringArgs[0])
beerocks_cli -> beerocks_cli: bml_update_wifi_credentials(\n ctx,\n al-mac.c_str())
beerocks_cli -> bml_internal: update_wifi_credentials(const sMacAddr &al_mac)
bml_internal -> controller: message_com::send_cmdu(\n m_sockMaster,\n ACTION_BML_WIFI_CREDENTIALS_UPDATE_REQUEST)
controller -> controller: send_cmdu_to_broker(\n AP_AUTOCONFIGURATION_RENEW_MESSAGE,\n al_mac, db.get_local_bridge_mac());
controller -> bml_internal: message_com::send_cmdu(\n m_sockMaster,\n ACTION_BML_WIFI_CREDENTIALS_UPDATE_RESPONSE)
@enduml
