' from backhaul_fsm_main

[*] --> INIT
INIT --> WAIT_ENABLE
WAIT_ENABLE --> ENABLED

ENABLED --> MASTER_DISCOVERY : local controller && local gw

MASTER_DISCOVERY --> WAIT_FOR_AUTOCONFIG_COMPLETE
WAIT_FOR_AUTOCONFIG_COMPLETE --> CONNECT_TO_MASTER
CONNECT_TO_MASTER --> CONNECTED
CONNECTED --> OPERATIONAL

