FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    autoconf \
    autogen \
    binutils \
    clang-format \
    cmake \
    curl \
    gcc \
    git \
    libjson-c-dev \
    libncurses-dev \
    libnl-genl-3-dev \
    libreadline-dev \
    libssl-dev \
    libtool \
    libzmq3-dev \
    ninja-build \
    pkg-config \
    python \
    python-yaml \
    python3 \
    python3-yaml \
    uuid-runtime \
    vim \
    && rm -rf /var/lib/apt/lists/*
