if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()

if (NOT ${PROJECT}_REVISION)
    execute_process(
        COMMAND "git" "rev-parse" "HEAD"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_STRIP_TRAILING_WHITESPACE 
        OUTPUT_VARIABLE ${PROJECT}_REVISION
    )
endif()
set(${PROJECT}_VERSION_MAJOR 1)
set(${PROJECT}_VERSION_MINOR 4)
set(${PROJECT}_VERSION_PATCH 0)
set(${PROJECT}_VERSION_STRING ${${PROJECT}_VERSION_MAJOR}.${${PROJECT}_VERSION_MINOR}.${${PROJECT}_VERSION_PATCH})
execute_process(COMMAND "date" "+%F %T" OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE ${PROJECT}_BUILD_DATE)
message(STATUS "MultiAP ${PROJECT} Version: ${${PROJECT}_VERSION_STRING}")
message(STATUS "MultiAP ${PROJECT} Build Date: ${${PROJECT}_BUILD_DATE}")
message(STATUS "MultiAP ${PROJECT} Revision: ${${PROJECT}_REVISION}")