name: Merge Bot

on:
  check_suite:
    types: [completed]
  status: # CI

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge when ready
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        labels: "MergeWhenReady"
        blocking-labels: "don't merge"
        checks_enabled: true
        reviewers: true
        method: rebase
        test: true # make the bot comment instead of taking action
